# DoctorService-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctorapp-v22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctorapp
      version: "v22"
  template:
    metadata:
      labels:
        app: doctorapp
        version: "v22"
    spec:
      containers:
      - name: doctorapp
        image: saketcontainerregistry.azurecr.io/doctorservice:v22
        ports:
        - containerPort: 8500
          name: https
